### ISSUE TITLE
Insta and Twitter icons moved to bottom 

### ISSUE THREAD

**Issue by amykuner** [fac21/agency-website-ecrc#21]
When you tab through the keyboard you have to go through a lot of options before you reach the main content and navbars, which might be an issue for non-sighted users! Would you consider moving your social media icons to the footer instead of the navbar?

**Comment by rosie-ollerenshaw** [comment]
We decided to keep the icons where they were and change the tab indexes instead. But we removed logo and replaced with text and replaces icons.
